import os
import json
import redis
import requests
from google import genai
from google.genai import types
from celery import Celery
from celery.exceptions import MaxRetriesExceededError

# --- Configuration ---
REDIS_URL = os.getenv("REDIS_URL", "redis://localhost:6379")
SETTINGS_KEY = "tts_settings"

redis_client = redis.from_url(REDIS_URL, decode_responses=True)

def load_settings():
    """Loads settings from Redis or environment variables"""
    settings_json = redis_client.get(SETTINGS_KEY)
    if settings_json:
        return json.loads(settings_json)
    else:
        # Default settings pointing to the new models
        return {
            "GEMINI_API_KEY": os.getenv("GEMINI_API_KEY", ""),
            "GEMINI_TTS_MODEL": os.getenv("GEMINI_TTS_MODEL", "gemini-2.5-flash-preview-tts"),
            "TTS_VOICE": os.getenv("TTS_VOICE", "Kore"),
            "TTS_PROMPT": os.getenv("TTS_PROMPT", ""),
            "SUCCESS_WEBHOOK_URL": os.getenv("SUCCESS_WEBHOOK_URL", ""),
            "ERROR_WEBHOOK_URL": os.getenv("ERROR_WEBHOOK_URL", "")
        }

celery_app = Celery("app.celery_worker", broker=REDIS_URL)

@celery_app.task(bind=True, max_retries=3, default_retry_delay=60, acks_late=True)
def generate_audio_task(self, text: str, phone_number: str):
    """
    Celery task to generate audio using the NEW google-genai library.
    """
    print(f"Starting audio generation task for: {phone_number} using NEW library google-genai.")
    settings = load_settings()
    
    try:
        api_key = settings.get("GEMINI_API_KEY")
        success_url = settings.get("SUCCESS_WEBHOOK_URL")
        if not api_key or not success_url:
            raise ValueError("API Key or Success Webhook URL are not configured.")

        # Correct way to instantiate the client with the API key in the new library
        client = genai.Client(api_key=api_key)

        # --- Step 1: Build the full prompt and configuration ---
        prompt = settings.get("TTS_PROMPT", "")
        full_content_prompt = f"{prompt}: {text}" if prompt else text
        
        print(f"Generating audio with full prompt: '{full_content_prompt}'")

        tts_config = types.GenerateContentConfig(
            response_modalities=["AUDIO"],
            speech_config=types.SpeechConfig(
                voice_config=types.VoiceConfig(
                    prebuilt_voice_config=types.PrebuiltVoiceConfig(
                        voice_name=settings.get("TTS_VOICE", "Kore"),
                    )
                )
            ),
        )

        # --- Step 2: Call the API ---
        response = client.models.generate_content(
            model=settings.get("GEMINI_TTS_MODEL"),
            contents=full_content_prompt,
            config=tts_config,
        )

        # --- Step 3: Extract the binary audio data ---
        audio_data = response.candidates[0].content.parts[0].inline_data.data

        if not audio_data:
            raise ValueError("No audio data was generated by the API.")

        # --- Step 4: Send the audio file to the webhook ---
        file_name = f"{phone_number}.mp3"
        files = {'file': (file_name, audio_data, 'audio/mpeg')}
        payload = {'phone_number': phone_number}

        print(f"Sending audio file to success webhook: {success_url}")
        post_response = requests.post(success_url, files=files, data=payload, timeout=30)
        post_response.raise_for_status()

        print(f"Task for {phone_number} completed successfully.")
        return {"status": "success", "phone_number": phone_number}

    except Exception as exc:
        print(f"Task for {phone_number} failed. Attempt {self.request.retries + 1} of {self.max_retries}. Error: {str(exc)}")
        try:
            self.retry(exc=exc)
        except MaxRetriesExceededError:
            print(f"Max retries exceeded for task {self.request.id} ({phone_number}). Sending error notification.")
            error_url = settings.get("ERROR_WEBHOOK_URL")
            if error_url:
                try:
                    error_payload = {
                        "task_id": self.request.id,
                        "phone_number": phone_number,
                        "original_text": text,
                        "error_message": f"Failed after {self.max_retries} retries: {str(exc)}"
                    }
                    requests.post(error_url, json=error_payload, timeout=10)
                except Exception as webhook_exc:
                    print(f"Failed to send error notification webhook: {str(webhook_exc)}")
            
            return {"status": "failed", "phone_number": phone_number, "error": str(exc)}